import ThemeRegistry from '@/theme/ThemeRegistry';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ReduxProvider } from '@/redux/provider';
import Toast from '@/components/Toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <ReduxProvider>
                <ThemeRegistry>
                    <body className={inter.className}>{children}</body>
                    <Toast />
                </ThemeRegistry>
            </ReduxProvider>
        </html>
    );
}
